float32 search_time
---
float32 ta_length
float32 ta_width # 
float32 ta_height #
float32[] start_pose #x,y,z,theta
float32[] plane_eq #a, b, c, d
float32[] direction # x,y,z transition area direction vector
geometry_msgs/Polygon boundary #boundary of quad
float32 slope
string state
