#goal_definition
int16 current_floor
geometry_msgs/PoseStamped building_loc
int16 target_floor
geometry_msgs/PoseStamped target_pose
---
#result_definition
uint16  error_code
string error_msg
string result
---
#feedback_definition
geometry_msgs/PoseStamped current_pose