float64 conf    # class confidence (0-1)
int64 x         # center of bounding box x-coordinate in image coordinates
int64 y         # center of bounding box y-coordinate in image coordinates
int64 height    # bounding box strech along y-axis in pixels
int64 width     # bounding box strech along x-axis in pixels
int16 id        # class id associated with bounding box
string label    # class name associated with bounding box
float64 pose_x #3d world pose X in camera frame of ref
float64 pose_y #3d world pose X in camera frame of ref
float64 pose_theta #3d world pose X in camera frame of ref